name: 'check-gradle-version'
description: 'GitHub Action for Gradle version verification'
author: 'madhead'
  gradlew:
    required: false
    default: 'gradlew'
    description: 'Relative path to gradlew executable'
runs:
  using: 'node12'
  main: 'dist/index.js'
